### ISSUE TITLE
[📄 Docs] 깃 위키 페이지 세팅하기

### ISSUE THREAD

**Issue by seochan99** [GDSC-DGU/gdsc-dgu#2]
## 🛠 Issue

협업을 위해 깃허브 위키에 프로젝트 이슈 사항을 기록하고 문서를 공동으로 관리
앞으로 업로드할 문서들을 편리하고, 체계적으로 관리하기 위해 메뉴(ex, 프로젝트 소개, 데일리, 회의록 등)를 선정해서 페이지를 세팅

## 📝 To-do

- [ ] 다른 개발 위키 페이지 조사하기
- [ ]  위키로 관리해야할 대상 선정하기(ex, 회의록, 기술 공유 등)
- [ ]  위키 관리 방식, 포맷 협의하기
- [ ]  각 페이지, 상위 메뉴 이름 등 정하기
- [ ]  깃 위키에 반영하기

**Comment by seochan99** [comment]
[레퍼런스 1 ](https://velog.io/@shyuuuuni/Github-Wiki-%EC%BB%A4%EC%8A%A4%ED%85%80-%ED%95%98%EA%B8%B0)
