### ISSUE TITLE
[🥹 Feedback] Project Feedback

### ISSUE THREAD

**Issue by shimseohyun** [GDSC-DGU/gdsc-dgu#26]
## 🛠 Issue
_Project Feedback_
너무 많은 페이지...
정말 고생하셨습니다.

## 📝 To-do

- [x] 전체 뷰 크기 수정
현재 전체 화면의 80%로 화면크기를 조절하고 계시네요...! 1200px이후는 100%가 되어야합니다...! 이때 내부 뷰의 크기는 1200px을 넘어가지 않습니다. 

`w-4/5`으로 최상단 화면을 정의하는 것 보다는

```
<section className="flex justify-center">
    <div className="max-w-[1200px] tablet:px-10 px-4">
       <div className="w-full">
           코드~~~~
```
으로 정의 해보는건 어떨까요?
`<section className="flex justify-center">` 아래로 정의된
내부 콘텐츠들이 `max-w-[1200px]`을 넘어가지 않고,
`tablet:px-10 px-4` 데스크탑과 테블릿에서는 좌우 패딩이 40px, 모바일에서는 16px로 정의되어 뷰 구현이 조금 더 수월하지 않을까 합니다.

- [x] 프로젝트 카드 서비스 소개 부분 height 고정.
최대 두줄이 들어갈 수 있게 부탁드립니다!
한줄이어도, 높이는 2줄 분량을 차지하고 있으면 좋겠어요. `hieght 값을 고정`해주면 되겠죠?
글자수가 넘어가는 경우 말줄임 표시로 처리하면 될 것 같아요.

- [x] 프로젝트 디테일 프로젝트 이미지 고정
화면을 줄일때, 프로젝트 이미지는 줄어들지 않고 우측에 있는 프로젝트 설명부분만 줄어들게 부탁드립니다!

- [x] 팀소개 섹션의 경우 토글로 접힐 수 있게 부탁드려요!
