### ISSUE TITLE
[🥹 Feedback] Seminar Feedback

### ISSUE THREAD

**Issue by shimseohyun** [GDSC-DGU/gdsc-dgu#27]
## 🛠 Issue
_Seminar Feedback_
너무 고생하셨어요 ㅜㅜ..............

## 📝 To-do

- [ ] Seminar Title 좌우 패딩 주세요!
![스크린샷 2024-04-19 오전 1 31 43](https://github.com/GDSC-DGU/gdsc-dgu/assets/117021241/73283d4e-d871-4627-9e86-3f6511ab643b)
px-3이 들어가야합니당

- [ ] Seminar Card....
이거 왜 ㅜㅜㅜ 하나하나 코딩하셨나요 그냥 이미지 넣으면 됩니다 ㅜㅜㅜㅜ
우측 태그만 살려주고 이미지로 넣어요!

- [ ] 디테일 페이지 사진 부분도 이미지로 부탁해요!

- [ ] Seminar Detial Title 좌우 패딩 주세요!
![스크린샷 2024-04-19 오전 1 34 31](https://github.com/GDSC-DGU/gdsc-dgu/assets/117021241/15c7728d-4e14-4e20-98

- [ ] 우측 두개는 그레이로 빼주세요~
![스크린샷 2024-04-19 오전 1 35 04](https://github.com/GDSC-DGU/gdsc-dgu/assets/117021241/a3763f9d-d5c0-4d95-877e-3d96672d8564)
bb-3df4105f4717)

- [ ] 패딩, gap 수정
![스크린샷 2024-04-19 오전 1 35 51](https://github.com/GDSC-DGU/gdsc-dgu/assets/117021241/22359676-bfbf-4b96-b707-6832cc207f97)

리뷰에 패딩 넣어주세요!

리뷰랑 리뷰카드 사이는 32px 리뷰리스트 사이간격은 16px입니다! 지금 다 1rem(16px)로 통일 되어있어요~~

**Comment by bianbbc87** [comment]
확인했습니다 감사합니다!
