### ISSUE TITLE
[Feature] Header

### ISSUE THREAD

**Issue by shimseohyun** [GDSC-DGU/gdsc-dgu#28]
## 🛠 Issue
Header 을 생성합니다.

## 📝 To-do

- [x] 해더 생성
- [x] Image Guide 생성
- [x] mobile view Swiper 추가

- [ ] const로 설정할 수 있는 것들은 설정해두기
