### ISSUE TITLE
[✨Feature] Member 페이지 반응형, 파비콘, GA

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/gdsc-dgu#29]
## 🛠 Issue
 페이지 반응형으로 수정 및 스타일 적용
파비콘, 메타데이터, GA 적용

## 📝 To-do

- [x] 피드백 수정
- [x] 멤버페이지 반응형
- [x] 새로 만든 폰트 H1,H2,H3 ..으로 수정
- [x] 컬러 시스템 수정
- [x] 파비콘
- [x] 메타데이터 - 썸네일 아직 없음 이슈로 서현님이 완성되면 달아주신다고 합니다! 
- [x] GA - gdsc용 계정 나중에 주신다고 하니 이후에 달겠슴다
