### ISSUE TITLE
[✨Feature] Timeline 피드백 사항 반영, Footer 제작

### ISSUE THREAD

**Issue by puretension** [GDSC-DGU/gdsc-dgu#30]
## 🛠 Issue
1차 PR 이후의 피드백 사항들(#18 + #24 + #25)을 반영하고 Footer를 제작합니다

## 📝 To-do
- [ ] 피드백 사항 반영을 통해 UI 구현 코드 개선
- [ ] 공통 폰트 및 컬러로 수정
- [ ] Footer 제작
- [ ] 타임라인 페이지 반응형
