### ISSUE TITLE
[✨Feature] Project Feedback 반영, 모션 라이브러리 적용

### ISSUE THREAD

**Issue by naarang** [GDSC-DGU/gdsc-dgu#31]
## 🛠 Issue

#22 - 지난 pr 피드백
#24, #26 - 스타일 수정하기

## 📝 To-do

- [x] 하드코딩 개선(constant 폴더에 만들기)
- [x] Font, Color, Breakpoint custom style 수정
- [x] #26 task 완료하기
- [x] framer-motion 라이브러리 적용하기
