### ISSUE TITLE
[💄Design] Seminar 페이지 스타일 양식 수정, 반응형 처리

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/gdsc-dgu#40]
## 🛠 Issue

 페이지 반응형으로 수정 및 스타일 적용
 현재 만들어진 세미나, 일반 세미나 디테일 페이지만 적용

## 📝 To-do

- [x] Seminar page 피드백 수정
- [x] desktop, tablet, mobile 반응형
- [x] 폰트 사이즈 H1 ~ H6, B, Cha, Btn으로 통일
- [x] 컬로 mono로 통일
- [x] 세미나 썸네일 png 이미지로 변경
- [x] 피그마 디자인에 따라 기타 여백, 사이즈 조정
